// Express-Course/react_lesson_nine/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Planets from './components/Planets';


class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>

        <Planets uri="http://localhost:3001/staticPlanets" />
        <hr />
        <Planets uri="http://localhost:3001/starTrekPlanets"/>
      </div>
    );
  }
}

export default App;

// Express-Course/planets/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Angular 2 Planets';
  staticPath: string = 'http://localhost:3001/staticPlanets';
  starTrekPath: string = 'http://localhost:3001/starTrekPlanets';
}
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
</div>
<hr/>
<div style="text-align:center">
  <div>
      <h2>Static Planet Data</h2>
      <h3>{{staticPath}}</h3>
      <app-planets
        [dataPath]="staticPath">
      </app-planets>
  </div>
  <hr/>
  <div>
      <h2>Live Planet Data</h2>
      <h3>{{starTrekPath}}</h3>
      <app-planets
        [dataPath]="starTrekPath">
      </app-planets>
  </div>
</div>
